services:
  api_gateway:
    build: ./api_gateway
    ports:
      - "80:80"
    depends_on:
      - postgres
    networks:
      - clearbalance-net

  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: clearbalance
      POSTGRES_PASSWORD: password
      POSTGRES_DB: clearbalance
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - clearbalance-net

volumes:
  postgres_data:

networks:
  clearbalance-net:
    driver: bridge