services:
  api_gateway:
    build: ./api_gateway
    ports:
      - "80:80"
      - "443:443"
    networks:
      - clearbalance-net
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    depends_on:
      - postgres

  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: clearbalance
      POSTGRES_PASSWORD: password
      POSTGRES_DB: clearbalance
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - clearbalance-net

volumes:
  postgres_data:

networks:
  clearbalance-net:
    driver: bridge