services:
  api_gateway:
    build: ./api_gateway
    ports:
      - "80:80"
      - "443:443"
    networks:
      - clearbalance-net
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    depends_on:
      - postgres
      - certbot

  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: clearbalance
      POSTGRES_PASSWORD: password
      POSTGRES_DB: clearbalance
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - clearbalance-net

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    networks:
      - clearbalance-net
    depends_on:
      - api_gateway

volumes:
  postgres_data:
  certbot_www:
  certbot_conf:

networks:
  clearbalance-net:
    driver: bridge