global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'services'
    static_configs:
      - targets:
        - 'user_service:8000'
        - 'debt_service:8000'
        - 'payment_service:8000'
        - 'notification_service:8000'
        - 'kafka:9092'
        - 'redis:6379'