FROM python:3.9-slim

WORKDIR /app

ENV PYTHONPATH="/app:${PYTHONPATH}"

RUN apt-get update && apt-get install -y \
	gcc \
	python3-dev \
	libpq-dev \
	&& rm -rf /var/lib/apt/lists/*

# Копируем зависимости отдельным слоем для кэширования
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Копируем миграции и код
COPY alembic.ini .
COPY migrations/ ./migrations/
COPY app/ ./app/

# Команда запуска с автоматическими миграциями
CMD ["sh", "-c", "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000"]