services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - clearbalance-net
    healthcheck:
      test: /bin/bash -c "echo stat | nc 127.0.0.1 2181 | grep -q Mode"
      interval: 10s
      timeout: 5s
      retries: 15
    volumes:
      - zookeeper-data:/var/lib/zookeeper/data

  kafka:
    image: confluentinc/cp-kafka:7.3.0
    depends_on:
      zookeeper:
        condition: service_healthy
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_MIN_INSYNC_REPLICAS: 1
    ports:
      - "9092:9092"
    networks:
      - clearbalance-net
    healthcheck:
      test: /bin/sh -c "kafka-topics --bootstrap-server localhost:9092 --list"
      interval: 15s
      timeout: 10s
      retries: 5
    volumes:
      - kafka-data:/var/lib/kafka/data

volumes:
  zookeeper-data:
  kafka-data:

networks:
  clearbalance-net:
    external: true