services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - clearbalance-net
    healthcheck:
      test: /bin/sh -c "echo ruok | socat - TCP:localhost:2181 | grep imok"
      interval: 10s
      timeout: 15s
      retries: 25
      start_period: 60s
    volumes:
      - zookeeper-data:/var/lib/zookeeper/data
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.3.0
    depends_on:
      zookeeper:
        condition: service_healthy
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
    networks:
      - clearbalance-net
    healthcheck:
      test: /bin/sh -c "kafka-topics --bootstrap-server localhost:9092 --list"
      interval: 25s
      timeout: 20s
      retries: 15
    volumes:
      - kafka-data:/var/lib/kafka/data
    ports:
      - "9092:9092"

networks:
  clearbalance-net:
    driver: bridge

volumes:
  zookeeper-data:
  kafka-data: