services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - clearbalance-net
    healthcheck:
      test: /bin/bash -c "echo stat | nc 127.0.0.1 2181 | grep -q Mode"
      interval: 10s
      timeout: 5s
      retries: 15
    volumes:
      - zookeeper-data:/var/lib/zookeeper/data
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.3.0
    depends_on:
      - zookeeper
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL: PLAINTEXT
      KAFKA_LISTENER_PORT: 9093
      KAFKA_LISTENER_NAME_INTERNAL: INSIDE
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093
      KAFKA_LISTENER_NAMES: INSIDE
      KAFKA_LISTENER_INTERNAL: INSIDE
      KAFKA_LISTENER_INTERNAL_PORT: 9093
    networks:
      - clearbalance-net
    healthcheck:
      test: /bin/bash -c "echo 'describe cluster' | kafka-console-consumer --bootstrap-server kafka:9093 --topic test --from-beginning --max-messages 1"
      interval: 20s
      timeout: 10s
      retries: 5
    volumes:
      - kafka-data:/var/lib/kafka/data
    ports:
      - "9093:9093"

networks:
  clearbalance-net:
    driver: bridge

volumes:
  zookeeper-data:
  kafka-data: