services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - clearbalance-net
    healthcheck:
      test: /usr/bin/zkOk.sh 127.0.0.1 2181
      interval: 20s
      timeout: 15s
      retries: 10
    volumes:
      - zookeeper-data:/var/lib/zookeeper/data
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.3.0
    depends_on:
      zookeeper:
        condition: service_healthy
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL: PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
    networks:
      - clearbalance-net
    healthcheck:
      test: /bin/sh -c "kafka-topics --bootstrap-server localhost:9093 --list"
      interval: 30s
      timeout: 20s
      retries: 5
    volumes:
      - kafka-data:/var/lib/kafka/data
    ports:
      - "9093:9093"

networks:
  clearbalance-net:
    driver: bridge

volumes:
  zookeeper-data:
  kafka-data: