services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - clearbalance-net
    healthcheck:
      test: /bin/bash -c "echo -e 'ruok' | nc 127.0.0.1 2181 | grep -q imok"
      interval: 10s
      timeout: 5s
      retries: 30
      start_period: 40s
    volumes:
      - zookeeper-data:/var/lib/zookeeper/data
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.3.0
    depends_on:
      zookeeper:
        condition: service_healthy
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
    networks:
      - clearbalance-net
    healthcheck:
      test: /bin/bash -c "kafka-topics --bootstrap-server localhost:9092 --list"
      interval: 15s
      timeout: 10s
      retries: 15
      start_period: 60s
    volumes:
      - kafka-data:/var/lib/kafka/data
    ports:
      - "9092:9092"

networks:
  clearbalance-net:
    driver: bridge

volumes:
  zookeeper-data:
  kafka-data: